In [ ]:
import pandas as pd
import numpy as np

df_dados = pd.read_excel('Dados Bibliograficos UEM_UZ_ISPQ 2025_2026.xls')

KeyError: "[('Direct', 'Ordem', 'NoLido', 'Dispensa', 'RevProva', 'celular', 'celularAlternativo', 'DataReg', 'HoraReg', 'OperReg')] not found in axis"

In [3]:
display(df_dados)

,Direct,Ordem,Ano,NoLido,candidato_codigo,apelido,nome,TipoDoc,DocIdent,Sexo,...,UZ_Cod_Opc2,UZ_Opc2,Dispensa,RevProva,Status,DataReg,HoraReg,OperReg,nuit,data_Nasc
0,NaN,NaN,2026,NaN,10019,SUARES,SONIA,BILHETE DE IDENTIDADE,1233444,FEMININO,...,35110.0,Economia (Beira) - Diurno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,344553521.0,2011-12-11
1,NaN,NaN,2026,NaN,10039,MUARAPAZ,CLÁUDIO ARMANDO,BILHETE DE IDENTIDADE,030106033801F,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177648922.0,2004-05-07
2,NaN,NaN,2026,NaN,10041,MBALANGO,YUNI ADELAIDE ANÍBAL,BILHETE DE IDENTIDADE,110107852412P,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131513240.0,2007-10-13
3,NaN,NaN,2026,NaN,10047,CHALE,IBRAIMO OMAR,BILHETE DE IDENTIDADE,070102840008F,MASCULINO,...,35209.0,Engenharia Eléctrica (Beira) - Nocturno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,123024631.0,1995-07-05
4,NaN,NaN,2026,NaN,10050,CUVACA,ANTONIO DOMINGOS,BILHETE DE IDENTIDADE,070108883250D,MASCULINO,...,35208.0,Engenharia Eléctrica (Beira) - Diurno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,174122997.0,2004-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34173,NaN,NaN,2026,NaN,65514,OMARGY,KAÍQUE IBRAIMO,PASSAPORTE,AB1061974,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146487483.0,2008-12-30
34174,NaN,NaN,2026,NaN,37179,COSSA,JOANA,BILHETE DE IDENTIDADE,110107076524A,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188948960.0,2009-01-01
34175,NaN,NaN,2026,NaN,65520,SITOE,MARTA SALVADOR,BILHETE DE IDENTIDADE,110208868345j,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189257074.0,2008-03-18
34176,NaN,NaN,2026,NaN,65469,CHICHAVA,LÉNON STEFAN CUSTÓDIO,BILHETE DE IDENTIDADE,090107809202D,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189452934.0,2009-01-27
34177,NaN,NaN,2026,NaN,63192,RAFAEL,LUCINIA DA FÁTIMA,BILHETE DE IDENTIDADE,070100473455I,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114387312.0,1986-08-22

In [4]:
display(df_dados.info())

<class 'pandas.DataFrame'>
RangeIndex: 34178 entries, 0 to 34177
Data columns (total 45 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Direct               0 non-null      float64
 1   Ordem                0 non-null      float64
 2   Ano                  34178 non-null  int64
 3   NoLido               0 non-null      float64
 4   candidato_codigo     34178 non-null  int64
 5   apelido              34177 non-null  str
 6   nome                 34177 non-null  str
 7   TipoDoc              34178 non-null  str
 8   DocIdent             34178 non-null  str
 9   Sexo                 34177 non-null  str
 10  EstCivil             34177 non-null  str
 11  pai_nascimento       34176 non-null  str
 12  ProvNasc             34176 non-null  str
 13  ProvRes              34176 non-null  str
 14  ProvCand             34177 non-null  str
 15  cod_preUni           34145 non-null  float64
 16  EscoPU               34177 non-null  str
 17  local_exame          34174 non-null  str
 18  TipoEst              0 non-null      float64
 19  AnocPU               34178 non-null  int64
 20  Classif              0 non-null      float64
 21  celular              34178 non-null  int64
 22  celularAlternativo   34178 non-null  int64
 23  distrito_nascimento  34176 non-null  str
 24  distrito_residencia  34176 non-null  str
 25  UEM_Cod_Opc1         26798 non-null  float64
 26  UEM_Opc1             26798 non-null  str
 27  UEM_Cod_Opc2         24059 non-null  float64
 28  UEM_Opc2             24059 non-null  str
 29  ISPQ_Cod_Opc1        95 non-null     float64
 30  ISPQ_Opc1            95 non-null     str
 31  ISPQ_Cod_Opc2        35 non-null     float64
 32  ISPQ_Opc2            35 non-null     str
 33  UZ_Cod_Opc1          9193 non-null   float64
 34  UZ_Opc1              9193 non-null   str
 35  UZ_Cod_Opc2          8216 non-null   float64
 36  UZ_Opc2              8216 non-null   str
 37  Dispensa             0 non-null      float64
 38  RevProva             0 non-null      float64
 39  Status               0 non-null      float64
 40  DataReg              0 non-null      float64
 41  HoraReg              0 non-null      float64
 42  OperReg              0 non-null      float64
 43  nuit                 34177 non-null  float64
 44  data_Nasc            34177 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(19), int64(5), str(20)
memory usage: 11.7 MB

None

In [5]:
display(df_dados.describe())

,Direct,Ordem,Ano,NoLido,candidato_codigo,cod_preUni,TipoEst,AnocPU,Classif,celular,...,UZ_Cod_Opc1,UZ_Cod_Opc2,Dispensa,RevProva,Status,DataReg,HoraReg,OperReg,nuit,data_Nasc
count,0.0,0.0,34178.0,0.0,34178.000000,34145.000000,0.0,34178.000000,0.0,3.417800e+04,...,9193.000000,8216.000000,0.0,0.0,0.0,0.0,0.0,0.0,3.417700e+04,34177
mean,NaN,NaN,2026.0,NaN,37987.101527,252.720838,NaN,2023.170578,NaN,8.593298e+08,...,35280.794953,35250.651899,NaN,NaN,NaN,NaN,NaN,NaN,1.645077e+08,2005-06-01 12:04:49.457822
min,NaN,NaN,2026.0,NaN,10019.000000,0.000000,NaN,1994.000000,NaN,5.010657e+07,...,35100.000000,35100.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1962-08-15 00:00:00
25%,NaN,NaN,2026.0,NaN,24430.500000,53.000000,NaN,2023.000000,NaN,8.477371e+08,...,35204.000000,35113.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.415376e+08,2004-08-14 00:00:00
50%,NaN,NaN,2026.0,NaN,38531.000000,141.000000,NaN,2024.000000,NaN,8.606555e+08,...,35212.000000,35210.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.738462e+08,2006-10-08 00:00:00
75%,NaN,NaN,2026.0,NaN,51569.750000,413.000000,NaN,2025.000000,NaN,8.718142e+08,...,35304.000000,35306.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.840510e+08,2008-01-09 00:00:00
max,NaN,NaN,2026.0,NaN,65520.000000,1103.000000,NaN,2025.000000,NaN,9.794014e+08,...,35701.000000,35701.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.213851e+08,2011-12-31 00:00:00
std,NaN,NaN,0.0,NaN,15728.250079,249.696454,NaN,2.957054,NaN,1.970118e+07,...,166.860458,144.186959,NaN,NaN,NaN,NaN,NaN,NaN,2.774116e+07,NaN

In [44]:
#Testes basicos
#display(df_dados.columns)
lsita = ["Direct", "Ordem", "NoLido", "Dispensa", "RevProva", "celular", "celularAlternativo", "DataReg", "HoraReg", "OperReg"]
#df_dados.drop(columns = lsita, inplace = True)
#display(df_dados.head())
lista2=["ISPQ_Opc1", "ISPQ_Cod_Opc2", "UZ_Cod_Opc1", "UZ_Opc1", "ISPQ_Opc2", "UZ_Opc2", "Status"]
#df_dados.drop(columns = lista2, inplace = True)
#display(df_dados.head())
df_dados.drop(columns=["ISPQ_Cod_Opc1", "UZ_Cod_Opc2", "nuit"], inplace=True)

KeyError: "['ISPQ_Cod_Opc1', 'UZ_Cod_Opc2', 'nuit'] not found in axis"

In [3]:
import pandas as pd
import numpy as np 

df_dados = pd.read_excel('Dados Bibliograficos UEM_UZ_ISPQ 2025_2026.xls')
display(df_dados)

,Direct,Ordem,Ano,NoLido,candidato_codigo,apelido,nome,TipoDoc,DocIdent,Sexo,...,UZ_Cod_Opc2,UZ_Opc2,Dispensa,RevProva,Status,DataReg,HoraReg,OperReg,nuit,data_Nasc
0,NaN,NaN,2026,NaN,10019,SUARES,SONIA,BILHETE DE IDENTIDADE,1233444,FEMININO,...,35110.0,Economia (Beira) - Diurno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,344553521.0,2011-12-11
1,NaN,NaN,2026,NaN,10039,MUARAPAZ,CLÁUDIO ARMANDO,BILHETE DE IDENTIDADE,030106033801F,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177648922.0,2004-05-07
2,NaN,NaN,2026,NaN,10041,MBALANGO,YUNI ADELAIDE ANÍBAL,BILHETE DE IDENTIDADE,110107852412P,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131513240.0,2007-10-13
3,NaN,NaN,2026,NaN,10047,CHALE,IBRAIMO OMAR,BILHETE DE IDENTIDADE,070102840008F,MASCULINO,...,35209.0,Engenharia Eléctrica (Beira) - Nocturno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,123024631.0,1995-07-05
4,NaN,NaN,2026,NaN,10050,CUVACA,ANTONIO DOMINGOS,BILHETE DE IDENTIDADE,070108883250D,MASCULINO,...,35208.0,Engenharia Eléctrica (Beira) - Diurno - UZ,NaN,NaN,NaN,NaN,NaN,NaN,174122997.0,2004-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34173,NaN,NaN,2026,NaN,65514,OMARGY,KAÍQUE IBRAIMO,PASSAPORTE,AB1061974,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146487483.0,2008-12-30
34174,NaN,NaN,2026,NaN,37179,COSSA,JOANA,BILHETE DE IDENTIDADE,110107076524A,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188948960.0,2009-01-01
34175,NaN,NaN,2026,NaN,65520,SITOE,MARTA SALVADOR,BILHETE DE IDENTIDADE,110208868345j,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189257074.0,2008-03-18
34176,NaN,NaN,2026,NaN,65469,CHICHAVA,LÉNON STEFAN CUSTÓDIO,BILHETE DE IDENTIDADE,090107809202D,MASCULINO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189452934.0,2009-01-27
34177,NaN,NaN,2026,NaN,63192,RAFAEL,LUCINIA DA FÁTIMA,BILHETE DE IDENTIDADE,070100473455I,FEMININO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114387312.0,1986-08-22

In [28]:
lista = ["Direct", "Ordem", "NoLido", "Dispensa", "RevProva", "celular", "celularAlternativo", "DataReg", "HoraReg", "OperReg", "ISPQ_Opc1", "ISPQ_Cod_Opc2", "UZ_Cod_Opc1", "UZ_Opc1", "ISPQ_Opc2", "UZ_Opc2", "Status", "ISPQ_Cod_Opc1", "UZ_Cod_Opc2", "nuit"]
#df_dados.drop(columns = lista, inplace = True)
display(df_dados.info())

<class 'pandas.DataFrame'>
RangeIndex: 34178 entries, 0 to 34177
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ano                  34178 non-null  int64
 1   candidato_codigo     34178 non-null  int64
 2   apelido              34177 non-null  str
 3   nome                 34177 non-null  str
 4   TipoDoc              34178 non-null  str
 5   DocIdent             34178 non-null  str
 6   Sexo                 34177 non-null  str
 7   EstCivil             34177 non-null  str
 8   pai_nascimento       34176 non-null  str
 9   ProvNasc             34176 non-null  str
 10  ProvRes              34176 non-null  str
 11  ProvCand             34177 non-null  str
 12  cod_preUni           34145 non-null  float64
 13  EscoPU               34177 non-null  str
 14  local_exame          34174 non-null  str
 15  AnocPU               34178 non-null  int64
 16  distrito_nascimento  34176 non-null  str
 17  distrito_residencia  34176 non-null  str
 18  UEM_Cod_Opc1         26798 non-null  float64
 19  UEM_Opc1             26798 non-null  str
 20  UEM_Cod_Opc2         24059 non-null  float64
 21  UEM_Opc2             24059 non-null  str
 22  data_Nasc            34177 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(3), str(16)
memory usage: 6.0 MB

None

In [30]:
lista2 =["Classif", "TipoEst"]
#df_dados.drop(columns = lista2, inplace = True)
#display(df_dados.head(6))
Colunas = ['UEM_Cod_Opc1', 'UEM_Opc1', 'UEM_Cod_Opc2', 'UEM_Opc2']
df_dados.dropna(subset = Colunas, thresh = 1, inplace = True)
display(df_dados)
#display(df_dados.columns)

,Ano,candidato_codigo,apelido,nome,TipoDoc,DocIdent,Sexo,EstCivil,pai_nascimento,ProvNasc,...,EscoPU,local_exame,AnocPU,distrito_nascimento,distrito_residencia,UEM_Cod_Opc1,UEM_Opc1,UEM_Cod_Opc2,UEM_Opc2,data_Nasc
0,2026,10019,SUARES,SONIA,BILHETE DE IDENTIDADE,1233444,FEMININO,Solteiro(a),Andorra,Estrangeiro,...,Colégio Delta,Chibuto,2012,Estrangeiro,PEMBA CIDADE,10100.0,Administração Pública - Diurno - UEM,10128.0,Arqueologia e Gestão do Património Cultural - ...,2011-12-11
1,2026,10039,MUARAPAZ,CLÁUDIO ARMANDO,BILHETE DE IDENTIDADE,030106033801F,MASCULINO,Solteiro(a),Mocambique,Nampula,...,Escola Secundária de Teacane,Cidade de Maputo,2022,CIDADE DE NAMPULA,KaMaxaquene,10300.0,Economia - Diurno - UEM,10302.0,Contabilidade e Finanças - Diurno - UEM,2004-05-07
2,2026,10041,MBALANGO,YUNI ADELAIDE ANÍBAL,BILHETE DE IDENTIDADE,110107852412P,FEMININO,Solteiro(a),Mocambique,Cidade de Maputo,...,Instituto Comercial de Maputo,Cidade de Maputo,2025,KaMpfumo,MATOLA CIDADE,10300.0,Economia - Diurno - UEM,10302.0,Contabilidade e Finanças - Diurno - UEM,2007-10-13
5,2026,10058,SARMENTO,NENGRA AURO,BILHETE DE IDENTIDADE,100107127647P,FEMININO,Solteiro(a),Mocambique,Província de Maputo,...,Escola Secundária de Machava Sede,Província de Maputo,2024,MATOLA CIDADE,MATOLA CIDADE,10300.0,Economia - Diurno - UEM,10302.0,Contabilidade e Finanças - Diurno - UEM,2007-06-27
6,2026,10062,SEBASTIÃO,LOIDA JOSEFA,BILHETE DE IDENTIDADE,110207815487J,FEMININO,Solteiro(a),Mocambique,Cidade de Maputo,...,Escola Secundária Josina Machel,Cidade de Maputo,2023,KaNlhamankulu,KaNlhamankulu,10208.0,Desenvolvimento e Educação de Infância - Diurn...,10204.0,Educação Ambiental (POR-III e BIO-II) - Diurno...,2004-09-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34173,2026,65514,OMARGY,KAÍQUE IBRAIMO,PASSAPORTE,AB1061974,MASCULINO,Solteiro(a),Mocambique,Província de Maputo,...,Escola Secundária de Machava Sede,Província de Maputo,2025,MATOLA CIDADE,MATOLA CIDADE,11200.0,Arquitectura e Planeamento Físico - Diurno - UEM,11110.0,Engenharia Informática - Diurno - UEM,2008-12-30
34174,2026,37179,COSSA,JOANA,BILHETE DE IDENTIDADE,110107076524A,FEMININO,Solteiro(a),Mocambique,Manica,...,Outra - Província de Maputo,Cidade de Maputo,2025,CHIMOIO CIDADE,MARRACUENE,10304.0,Gestão - Diurno - UEM,11036.0,Geologia e Pesquisa Mineral - Diurno - UEM,2009-01-01
34175,2026,65520,SITOE,MARTA SALVADOR,BILHETE DE IDENTIDADE,110208868345j,FEMININO,Solteiro(a),Mocambique,Cidade de Maputo,...,Desconhecida - Cidade de Maputo,Cidade de Maputo,2025,KaNlhamankulu,KaNlhamankulu,10600.0,Direito - Diurno - UEM,10500.0,Jornalismo - Diurno - UEM,2008-03-18
34176,2026,65469,CHICHAVA,LÉNON STEFAN CUSTÓDIO,BILHETE DE IDENTIDADE,090107809202D,MASCULINO,Solteiro(a),Mocambique,Gaza,...,Escola Secundária do Xai-Xai,Chongoene,2025,CIDADE DE XAI-XAI,CIDADE DE XAI-XAI,11104.0,Engenharia Eléctrica - Diurno - UEM,11110.0,Engenharia Informática - Diurno - UEM,2009-01-27
34177,2026,63192,RAFAEL,LUCINIA DA FÁTIMA,BILHETE DE IDENTIDADE,070100473455I,FEMININO,Solteiro(a),Mocambique,Sofala,...,Escola Secundária de Dondo,Cidade de Maputo,2007,DONDO,KaMpfumo,10601.0,Direito - Nocturno - UEM,10101.0,Administração Pública - Nocturno - UEM,1986-08-22

In [ ]:
coluna = ['UEM_Opc1', 'UEM_Opc2', 'EscoPU', 'local_exame', 'distrito_nascimento', 'distrito_residencia', 'EscoPU']
#df_dados[coluna] = df_dados [coluna].str.title()
#display(df_dados.info())
#
df_analise = df_dados.copy()
df_analise ['UEM_Cod_Opc2'] = df_analise ['UEM_Cod_Opc2'].fillna(0)
df_analise ['UEM_Opc2'] = df_analise ['UEM_Opc2'].fillna('Sem Opcao')
#display(df_analise.sample(20))
#display(df_analise.describe())
for col in coluna:
    df_analise[col] = df_analise[col].str.strip().str.title()
    
df_analise['candidato_codigo'].duplicated().sum()
df_analise['candidato_codigo'].is_unique